# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python"
  children:
    cluster:
      hosts:
        master:
          ansible_host: 192.168.100.10
        node1:
          ansible_host: 192.168.100.11
        node2:
          ansible_host: 192.168.100.12
